### ISSUE TITLE
Design Blocks Gallery button disappears when clicking on it

### ISSUE THREAD

**Issue by arkofno** [witsec/mobirise-design-blocks#1]
So basically, when you import the extension, you get this button to add blocks.
![image](https://user-images.githubusercontent.com/93203801/150756519-b26aca37-0164-410c-86b0-3a55738682ce.png)

When you click on it the button disappears and the selection screen pops up.
![image](https://user-images.githubusercontent.com/93203801/150756957-d4d37399-7531-4d8a-a3f5-c61cbaf04a9f.png)

But now, whatever I do (importing a block, canceling, closing the selection screen) the button doesn't come back and the bar on the top remains as it was
![image](https://user-images.githubusercontent.com/93203801/150757299-4075d87b-b9f4-4640-a4e0-ed5c005bc4df.png)

Only way to recover it is to re-import the extension, or open another site and then come back to the one I'm working on.
Mobirise version 5.5.8

**Comment by witsec** [comment]
Make sure you have "Show All Views" enabled in the app settings, that should do the trick.
Let me know how it goes.

I'm planning to move the Gallery button somewhere else, so we don't have this issue anymore.

**Comment by arkofno** [comment]
worked, thanks , you should put a note somewhere, its easy to walk over
