### ISSUE TITLE
"Design Block" icon disappears after clicking on it

### ISSUE THREAD

**Issue by HerniHdez** [witsec/mobirise-design-blocks#2]
Hi there,

Have you suffered this issue?

I'm running last Mobirise version, 5.6.13, and when I click on the "Design blocks" icon, it opens the dialog for adding/searching but the icon disappears and I can't add new "design blocks" unless I close and open the app again.

I'm using a standard template to make the screenshots, but I have tested with other different projects.

Before clicking:
![Captura witsec 1](https://user-images.githubusercontent.com/51020632/203277284-bfde4782-925d-4d8e-a070-1039340bd390.jpg)

Dialog opens (the icon has disappear):
![Captura witsec 2](https://user-images.githubusercontent.com/51020632/203277031-820e9b1a-8085-46d3-8736-25b034d16d9e.jpg)

After closing the dialog (the "Design blocks" icon is no longer available):
![Captura witsec 3](https://user-images.githubusercontent.com/51020632/203277036-2bdc3d9a-c1c3-4629-b9a2-6f8574195b2a.jpg)

Best regards,
HerniHdez

**Comment by witsec** [comment]
Hi HerniHdez,

That's a known thing. You can work around it by enabling "Show All Views" in the App settings. That way, the icon will always stay there.
In the next version, I'm moving the icon somewhere else, so this issue is a thing of the past.

**Comment by HerniHdez** [comment]
Hi witsec,

Thanks, it works great, and thanks for the info about the app option "Show All Views", I was missing that icons after updating from an old version of Mobirise.

Best regards,
HerniHdez

**Comment by witsec** [comment]
Glad to hear it's working well again!
